export const zh = {
  pairSubmitting: "正在提交绑定请求…", pairSubmittingDetail: "正在把设备名称发送到电脑，请稍候。", pairSubmittingHint: "无需重复点击；提交失败后可以重试。", pairWaiting: "等待电脑确认", pairWaitingHint: "打开电脑「设置 → 手机收集」，核对设备名称并点击确认。本页会自动更新，无需刷新。", pairSuccess: "绑定成功，现在可以发送到归知了。",
  appearance: "外观", themeSystem: "跟随系统", themeLight: "浅色", themeDark: "深色",
  title: "手机收集", tagline: "先收好，回到电脑再慢慢整理。", compose: "收集", history: "近期记录", help: "设备与帮助", input: "链接、分享口令或文字", placeholder: "粘贴链接、抖音 / 小红书分享口令，或记下一段想法…",
  auto: "自动识别", urls: "采集链接", text: "保存文字", send: "发送到归知", sending: "发送中…", accepted: "服务端已接收，电脑上线后会自动取回。", pending: "待发送 · 草稿仅保存在此手机", offline: "当前离线，联网后请点击发送。", count: "将创建 {n} 个采集项", empty: "还没有记录", refresh: "刷新", received: "桌面已接收", expired: "已过期，未交付", server: "服务端已接收", expires: "未交付到期时间", pair: "绑定这台手机", name: "设备名称", waiting: "请在电脑上确认这台手机的绑定请求", paired: "已绑定", unpaired: "请在电脑的「设置 → 手机收集」中生成二维码，用此手机扫码绑定。", install: "安卓：使用 Chrome 菜单「安装应用」后，可在系统分享菜单选择归知。鸿蒙和其他浏览器若不支持分享接入，可用粘贴入口。", iphone: "iPhone：安装“发送到归知”快捷指令后，填写此服务地址和专用凭证。", privacy: "内容经 HTTPS 传输，公共服务能读取暂存内容。未交付内容保留 30 天；电脑确认后清除主库正文，回执保留 30 天；加密备份副本最多保留 7 天。", shortcut: "生成快捷指令凭证", revoke: "撤销快捷指令凭证", secret: "仅显示这一次，请复制到快捷指令的配置中", failed: "操作失败", loadError: "读取失败，请重试", draftList: "待发送的分享草稿", remove: "删除草稿", back: "返回", completed: "采集完成", processing: "正在采集", canceled: "已取消", duplicate: "内容重复", login_required: "需在电脑上登录后重试", rate_limited: "平台限流", network: "网络错误", capture_failed: "采集失败，请到电脑查看", incomplete: "内容不完整，请到电脑查看", protocol_mismatch: "版本不兼容，请升级", invalid_invite: "邀请码无效", unauthorized: "设备未绑定或凭证已撤销", daily_limit: "今日采集项已达上限，草稿已保留", inbox_full: "收件箱已满，请先在电脑取件", rate_limited_api: "请求过于频繁，请稍后重试", request_conflict: "此请求编号已用于其他内容", pairing_expired: "二维码已过期，请在电脑重新生成", pairing_claimed: "二维码已被申请，请在电脑核对", input_too_large: "输入超过 32 KiB", too_many_links: "单次最多 20 个链接", no_links: "没有可采集的链接", empty_input: "请先输入内容", invalid_input: "输入格式无效", saved: "已保存", copy: "复制凭证", copied: "已复制", draftWarning: "浏览器清理数据会删除待发送草稿", installShortcut: "下载 iPhone 快捷指令", shortcutUnavailable: "iPhone 安装文件须在 macOS 签名后提供；当前尚未完成真机验收",
};
export const en: typeof zh = {
  pairSubmitting: "Submitting pairing request…", pairSubmittingDetail: "Sending your device name to the desktop. Please wait.", pairSubmittingHint: "No need to click again. You can retry if this fails.", pairWaiting: "Waiting for desktop confirmation", pairWaitingHint: "Open Settings → Mobile capture on your desktop, check the device name and confirm. This page updates automatically.", pairSuccess: "Phone paired. You can now send to GuiZhi.",
  appearance: "Appearance", themeSystem: "System", themeLight: "Light", themeDark: "Dark",
  title: "Mobile capture", tagline: "Save it now. Make sense of it at your desk.", compose: "Capture", history: "Recent", help: "Devices & help", input: "Links, shared text or notes", placeholder: "Paste links, a shared post, or a thought…", auto: "Auto", urls: "Capture links", text: "Save text", send: "Send to GuiZhi", sending: "Sending…", accepted: "Accepted by server. Your desktop will collect it when online.", pending: "Not sent · Draft on this phone only", offline: "Offline. Send when connected.", count: "Creates {n} capture items", empty: "No records yet", refresh: "Refresh", received: "Received by desktop", expired: "Expired before delivery", server: "Accepted by server", expires: "Undelivered expiry", pair: "Pair this phone", name: "Device name", waiting: "Confirm this phone on your desktop", paired: "Paired", unpaired: "Open Settings → Mobile capture on your desktop and scan the pairing QR code.", install: "Android: install from Chrome's menu to share to GuiZhi. On HarmonyOS or unsupported browsers, paste into this page.", iphone: "iPhone: install Send to GuiZhi and configure this service address and a dedicated credential.", privacy: "HTTPS transport. The public service can read queued content. Undelivered content expires in 30 days; payloads are cleared after desktop acknowledgement. Receipts last 30 days; encrypted backup copies expire within 7 days.", shortcut: "Create shortcut credential", revoke: "Revoke shortcut credentials", secret: "Shown once. Copy this into your shortcut configuration.", failed: "Action failed", loadError: "Could not load. Retry.", draftList: "Unsent share drafts", remove: "Delete draft", back: "Back", completed: "Completed", processing: "Processing", canceled: "Canceled", duplicate: "Duplicate", login_required: "Sign in and retry on desktop", rate_limited: "Platform rate limited", network: "Network error", capture_failed: "Capture failed; see desktop", incomplete: "Incomplete; see desktop", protocol_mismatch: "Incompatible version; update required", invalid_invite: "Invalid invitation", unauthorized: "Device is unpaired or revoked", daily_limit: "Daily limit reached. Draft retained.", inbox_full: "Inbox full. Collect on desktop first.", rate_limited_api: "Too many requests. Try later.", request_conflict: "Request ID already used for other content", pairing_expired: "QR expired. Generate a new one.", pairing_claimed: "Pairing already requested; check desktop", input_too_large: "Input exceeds 32 KiB", too_many_links: "At most 20 links per submission", no_links: "No links found", empty_input: "Enter something first", invalid_input: "Invalid input", saved: "Saved", copy: "Copy credential", copied: "Copied", draftWarning: "Clearing browser data removes unsent drafts", installShortcut: "Download iPhone shortcut", shortcutUnavailable: "A macOS-signed installation file is required. iPhone acceptance is still pending.",
};
