import { reconstructionFixture } from "./reading-reconstruction-fixture";

/** 图解验收素材为人工构造，不代表模型生成或研究结论。 */
export function readingSvgFixture() {
  const page = reconstructionFixture();
  page.reconstruction.interactions = [];
  page.reconstruction.outline.title = "把想法整理成知识";
  page.design.html = `<main><header><p class="eyebrow">阅读方法 · 图解笔记</p><h1>把想法整理成知识</h1><p>收集之后，怎样让信息真正留下来？从记录到理解，再到建立联系，用三个简单的视角梳理自己的阅读过程。</p><nav><a href="#flow">阅读流程 ↗</a><a href="#compare">概念对照 ↗</a><a href="#relation">知识关系 ↗</a></nav></header>
<section id="flow"><h2>01 让阅读留下可用的线索</h2><p>先保留让你停下来的内容，再用自己的话解释它，最后联系已有经验。这张流程图表达步骤顺序，不代表完成时间或效果比例。</p><figure>
<svg viewBox="0 0 320 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="flow-title" aria-describedby="flow-desc">
<title id="flow-title">记录、理解与联系的阅读流程</title><desc id="flow-desc">记录值得保留的内容，用自己的话理解，再联系已有经验。</desc>
<defs><linearGradient id="flow-wash" x1="0" y1="0" x2="1" y2="1"><stop offset="0" class="wash-start"/><stop offset="1" class="wash-end"/></linearGradient><marker id="flow-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M1 1L9 5L1 9" fill="none" class="connector" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></marker></defs>
<g transform="translate(20 10)"><rect width="280" height="70" rx="16" fill="url(#flow-wash)"/><text x="140" y="28" text-anchor="middle" class="label"><tspan x="140">记录</tspan><tspan x="140" dy="25" class="sub-label">保留值得再读的内容</tspan></text></g>
<path d="M160 84V112" class="flow-link connector" fill="none" stroke-width="2"/>
<g transform="translate(20 120)"><rect width="280" height="70" rx="16" class="node"/><text x="140" y="28" text-anchor="middle" class="label"><tspan x="140">理解</tspan><tspan x="140" dy="25" class="sub-label">用自己的话解释</tspan></text></g>
<path d="M160 194V222" class="connector" stroke-width="2" marker-end="url('#flow-arrow')"/>
<g transform="translate(20 230)"><rect width="280" height="60" rx="16" class="node"/><text x="140" y="36" text-anchor="middle" class="label">联系已有经验</text></g></svg><figcaption>从摘录走向理解，每一步都留下自己的思考。</figcaption></figure></section>
<section id="compare"><h2>02 区分保存与理解</h2><p>保存回答“在哪里”，理解回答“为什么”。两者可以互相补充，图中的相同面积只用于并列呈现，没有统计含义。</p><figure>
<svg viewBox="0 0 320 180" role="img" aria-label="保存与理解的概念对照"><defs><clipPath id="compare-clip"><rect x="10" y="10" width="300" height="160" rx="16"/></clipPath></defs><g clip-path="url(#compare-clip)"><rect x="10" y="10" width="300" height="160" class="node"/><path d="M160 20V160" class="connector" stroke-dasharray="4 6"/><text x="85" y="60" class="label" text-anchor="middle">保存</text><text x="235" y="60" class="label" text-anchor="middle">理解</text><text x="85" y="103" class="sub-label" text-anchor="middle">保留原始信息</text><text x="235" y="103" class="sub-label" text-anchor="middle">说清自己的认识</text><text x="85" y="136" class="sub-label" text-anchor="middle">便于再次查找</text><text x="235" y="136" class="sub-label" text-anchor="middle">便于解释与应用</text></g></svg><figcaption>保存提供线索，理解形成自己的表达。</figcaption></figure></section>
<section id="relation"><h2>03 在知识之间建立联系</h2><p>把新观点与经验、问题连接起来，可以成为下一次阅读的起点。连线表示关联，并不声明因果关系或重要性排序。</p><figure>
<svg viewBox="0 0 320 240" role="img" aria-label="新观点连接已有经验和待解问题"><defs><radialGradient id="relation-wash"><stop offset="0" class="wash-start"/><stop offset="1" class="wash-end"/></radialGradient></defs><g class="connector" fill="none" stroke-width="2"><path d="M160 80L85 160M160 80L235 160"/></g><circle cx="160" cy="65" r="50" fill="url(#relation-wash)"/><circle cx="85" cy="175" r="55" class="node"/><circle cx="235" cy="175" r="55" class="node"/><g text-anchor="middle" dominant-baseline="central" font-size="17" font-weight="600" fill="var(--theme-text)"><text x="160" y="65">新观点</text><text x="85" y="175">已有经验</text><text x="235" y="175">待解问题</text></g></svg><figcaption>通过关联，让下一次阅读有迹可循。</figcaption></figure></section></main>`;
  page.design.css = `html{--theme-surface:#f8f7f3;--theme-text:#223c40;--theme-accent:#26756d;--theme-node:#e5efea;--theme-wash-start:#c9e4d6;--theme-wash-end:#e7f1e6}html[data-theme=dark]{--theme-surface:#142526;--theme-text:#e1eeea;--theme-accent:#82c9b8;--theme-node:#243f3e;--theme-wash-start:#31594e;--theme-wash-end:#274541}main{max-width:820px;margin:auto;padding:28px 24px 60px}h1{font-size:34px;line-height:1.3;margin:12px 0 22px}h2{font-size:23px;margin:0 0 14px}.eyebrow{color:var(--theme-accent);font-size:14px;letter-spacing:2px}nav{display:flex;flex-wrap:wrap;gap:18px;margin:20px 0}nav a{font-size:15px;color:var(--theme-accent)}section{padding:28px 0;border-top:1px solid var(--theme-node)}figure{margin:24px auto;max-width:440px}figure svg{display:block;width:100%;height:auto}.node{fill:var(--theme-node)}.label{font-size:19px;font-weight:600;fill:var(--theme-text)}.sub-label{font-size:16px;font-weight:400;fill:var(--theme-text)}.connector{stroke:var(--theme-accent)}.flow-link{marker-end:url(#flow-arrow)}.wash-start{stop-color:var(--theme-wash-start)}.wash-end{stop-color:var(--theme-wash-end)}figcaption{font-size:14px;text-align:center;margin-top:14px;color:var(--theme-text)}@media(max-width:480px){main{padding:20px 18px}h1{font-size:28px}h2{font-size:21px}figure{margin:20px 0}}`;
  return page;
}
